### ISSUE TITLE
Support inlining critical css / js

### ISSUE THREAD

**Issue by PascalReintjens** [JuKu/JuKuCMS#190]
While resolving #188 it would be also quite beneficial to have support to be able to inline critical ccs / js, as well as support splitting css into header and footer, like it's already present for js-files.

**Comment by JuKu** [comment]
nice idea!
But this means also that css / js cannot be cached from browser.

**Comment by PascalReintjens** [comment]
> But this means also that css / js cannot be cached from browser.

That is true, but there are cases where the performance benefit from inlining can be higher than from caching. Furthermore, not inlining critical css will result in a point penalty in google pagespeed. We should decide later wether we can ignore this pagespeed rule (in case it regresses performance) but neverless it would be great to have this option available.

**Comment by JuKu** [comment]
I have moved this to milestone 0.2.0, so we will implement this in the actual milestone.

**Comment by PascalReintjens** [comment]
After thinking about this a little bit, it is clear that we can already realize this by directly putting in the code into the corresponding .tpl file or for plugins using {$HEADER} and {$FOOTER}
