### ISSUE TITLE
Set name to RocketCMS

### ISSUE THREAD

**Issue by JuKu** [JuKu/JuKuCMS#200]
Set name to RocketCMS.

  - [x] remove old JuKuCMS name
  - [x] remove name suggestions
  - [x] replace logo

**Comment by PascalReintjens** [comment]
Done. 

We're using the same image as for the default style favicon:

https://www.iconfinder.com/icons/1688851/campaign_launch_rocket_speed_icon
Free for commercial use; without link back.
