### ISSUE TITLE
Meta description

### ISSUE THREAD

**Issue by JuKu** [JuKu/JuKuCMS#203]
Add a meta description to every page.

  - [x] charset
  - [x] description
  - [x] keywords (google wouldn't look into this meta tag anymore)
  - [x] author
  - ~~viewport~~ (it's design specific)
  - ~~og:locale~~
  - [x] robots
  - [x] canoncials (to avoid duplicate content)

**Comment by JuKu** [comment]
See also:
https://www.sistrix.de/frag-sistrix/onpage-optimierung/meta-element-meta-tag/welche-metatags-sind-seo-relevant-und-welche-nicht/

**Comment by PascalReintjens** [comment]
> @PascalReintjens Should we also support meta tag "viewport"?

Shouldn't this meta tag be directly used in the style itself? What further should we support?

Further thoughts:
- The robots meta tag should be definitively supported
- What about the facebook open graph meta tags like og:type, og:title, og:description, og:url, og:image?
- What about canonicals?

**Comment by JuKu** [comment]
@PascalReintjens robots tag is included, facebook open graph tags are another issue #204 and canoncials are also already implemented. :)
