### ISSUE TITLE
Api to send mails

### ISSUE THREAD

**Issue by JuKu** [JuKu/JuKuCMS#51]
We should add an api to send mails.
This api should support SMTP mail and also php mail function. In global settings user can choose which option is used.

Supported mail types:
 - plain text mail
 - html mail

**Package**: com.jukusoft.cms.mail
**Class** (example name): MailApi

Methods (example):
 - sendPlainMail ($to, string $subject, string $content) : bool
 - sendHTMLMail (...) : bool

Important! Plugins should able to add options!
It should be possible to send mails to more than one user.

Other packages & plugins should use this api to send mails from board.

**Comment by JuKu** [comment]
@PascalReintjens Willst du dich vllt. darum kümmern?
Das dazugehörige package müsste "com.jukusoft.cms.mail" heißen.

**Comment by PascalReintjens** [comment]
@JuKu Since this is needed soon and I won't have enough time in the coming days, I'd recommend that you should implement this

**Comment by JuKu** [comment]
@PascalReintjens No problem!
Thanks for your answer!
